server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pb?characterEncoding=utf8&useSSL=false&useLocalSessionState=true&serverTimezone=GMT
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: classpath:/static
      suffix: .html
  thymeleaf:
    cache: false


graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

graphiql:
  mapping: /graphql
  endpoint: /graphql
  enabled: true
