server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_domain?characterEncoding=utf8&useSSL=false&useLocalSessionState=true&serverTimezone=GMT
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
