server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pb?characterEncoding=utf8&useSSL=false&useLocalSessionState=true&serverTimezone=GMT
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false


graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

#图形化界面
#graphiql:
#  mapping: /graphql
#  endpoint: /graphql
#  enabled: true
